" Set cursor stlye: block in visual mode, pipe in insert mode, half height
" when entering a command, underline when replacing 
set guicursor=n-v-c:block-Cursor,o:hor50-Cursor,r:hor15-Cursor,i-ci:ver25-Cursor,a:blinkon0
" defauly agimrLtT
" Remove scroll bars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L
set guioptions-=b

" Disable bell. Must be disabled after gui is loaded
set visualbell t_vb=                    " Turn off bell

set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 10


