#!/bin/bash


# Set alias for confirm_yn. Required as it isn't in the path yet
confirm_yn=./scripts/confirm_yn


##### LITE INSTALL #####
# TODO: lite install


##### DOTFILES #####
if $confirm_yn "Install dotfiles?" ; then
    olddir="$(pwd)"
	cd dotfiles
	for f in * ; do
		ln -s $(pwd)/$f ~/.$f
	done
	cd "$olddir"
fi


##### VIM #####
if [ ! -d ~/.vim ] && $confirm_yn "Set up vim?" ; then
	ln -s $(pwd)/vim ~/.vim
	git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim	
    vim +PluginInstall +qall
fi


##### SCRIPTS #####
if [ ! -d ~/bin ] && $confirm_yn "Copy scripts to bin?" ; then
	ln -s $(pwd)/scripts ~/bin
fi


##### SOFTWARRE #####
#TODO: instal software (python, sublime, etc)


##### SHELL TOOLS #####
#TODO: install shell tools (tree, etc)


##### PYTHON #####
#TODO: install python packages


##### R #####
#TODO: install R packages


##### CTAGS #####
#TODO: install CTAGS


##### MAC #####
#TODO: install files specific to mac
