#!/bin/bash
helpstr='
Extract an archived or compressed file base on extension

Usage:
    extract file

File must end with a recognized format for an archive method
Ex. `helpstr foo.zip`
'

if [ -f $1 ] ; then
    case $1 in
        -h|--help)   echo "$helpstr" ; exit 0 ;; 
        *.tar.bz2)   tar xvjf "$1"     ;;
        *.tar.gz)    tar xvzf "$1"     ;;
        *.bz2)       bunzip2 "$1"      ;;
        *.rar)       Unrat x "$1"      ;;
        *.gz)        gunzip "$1"       ;;
        *.tar)       tar xvd "$1"      ;;
        *.tbz2)      tar xvjf "$1"     ;;
        *.tgz)       tar xvzf "$1"     ;;
        *.zip)       unzip "$1"        ;;
        *.Z)         uncompress "$1"   ;;
        *.7z)        7z x "$1"         ;;
        *.lzo)       lzop -x "$1"      ;;
        *)           echo "'$1' cannot be extracted via >extract<" ;;
   esac
else
   echo "'$1' is not a valid file!"
fi
